{% set name = "sentinelhub" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b876a0811f5f7a4f396e4f985f73a3ae34a7abb5690d01ecaf3c2bfb21fb77e1

build:
  noarch: python
  number: 0
  entry_points:
    - sentinelhub=sentinelhub.commands:main_help
    - sentinelhub.aws=sentinelhub.commands:aws
    - sentinelhub.config=sentinelhub.commands:config
    - sentinelhub.download=sentinelhub.commands:download
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - pip
    - python >=3.5

  run:
    - aenum >=2.1.4
    - attrs >=18.2.0
    - boto3
    - botocore
    - click
    - numpy
    - oauthlib
    - pillow
    - pyproj
    - python >=3.5
    - python-dateutil
    - requests
    - requests-oauthlib
    - shapely
    - tifffile
    - utm
    - wheel
    - dataclasses-json

test:
  imports:
    - sentinelhub
    - sentinelhub.download
  commands:
    - sentinelhub --help
    - sentinelhub.aws --help
    - sentinelhub.config --help
    - sentinelhub.download --help

about:
  home: https://github.com/sentinel-hub/sentinelhub-py
  license: CC-BY-SA-4.0
  license_family: CC
  license_file: LICENSE.md
  summary: Sentinel Hub Utilities
  doc_url: https://pypi.org/project/sentinelhub/
  dev_url: https://github.com/sentinel-hub/sentinelhub-py

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - benhuff
    - mxr-conda
